<?php

namespace Database\Seeders;

use App\Models\Nationalitie;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class NationalitieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('nationalities')->delete();


        $nationalities = [
            ['name' => json_encode(['ar' => 'أفغاني', 'en' => 'Afghan'])],
            ['name' => json_encode(['ar' => 'ألباني', 'en' => 'Albanian'])],
            ['name' => json_encode(['ar' => 'جزائري', 'en' => 'Algerian'])],
            ['name' => json_encode(['ar' => 'أندوري', 'en' => 'Andorran'])],
            ['name' => json_encode(['ar' => 'أنغولي', 'en' => 'Angolan'])],
            ['name' => json_encode(['ar' => 'أرجنتيني', 'en' => 'Argentine'])],
            ['name' => json_encode(['ar' => 'أرميني', 'en' => 'Armenian'])],
            ['name' => json_encode(['ar' => 'أسترالي', 'en' => 'Australian'])],
            ['name' => json_encode(['ar' => 'نمساوي', 'en' => 'Austrian'])],
            ['name' => json_encode(['ar' => 'أذربيجاني', 'en' => 'Azerbaijani'])],
            ['name' => json_encode(['ar' => 'باهامي', 'en' => 'Bahamian'])],
            ['name' => json_encode(['ar' => 'بحريني', 'en' => 'Bahraini'])],
            ['name' => json_encode(['ar' => 'بنغلاديشي', 'en' => 'Bangladeshi'])],
            ['name' => json_encode(['ar' => 'بربادوسي', 'en' => 'Barbadian'])],
            ['name' => json_encode(['ar' => 'بيلاروسي', 'en' => 'Belarusian'])],
            ['name' => json_encode(['ar' => 'بلجيكي', 'en' => 'Belgian'])],
            ['name' => json_encode(['ar' => 'بليزي', 'en' => 'Belizean'])],
            ['name' => json_encode(['ar' => 'بنيني', 'en' => 'Beninese'])],
            ['name' => json_encode(['ar' => 'بوتاني', 'en' => 'Bhutanese'])],
            ['name' => json_encode(['ar' => 'بوليفي', 'en' => 'Bolivian'])],
            ['name' => json_encode(['ar' => 'بوسني', 'en' => 'Bosnian'])],
            ['name' => json_encode(['ar' => 'بوتسواني', 'en' => 'Botswanan'])],
            ['name' => json_encode(['ar' => 'برازيلي', 'en' => 'Brazilian'])],
            ['name' => json_encode(['ar' => 'بروني', 'en' => 'Bruneian'])],
            ['name' => json_encode(['ar' => 'بلغاري', 'en' => 'Bulgarian'])],
            ['name' => json_encode(['ar' => 'بوركينابي', 'en' => 'Burkinabe'])],
            ['name' => json_encode(['ar' => 'بوروندي', 'en' => 'Burundian'])],
            ['name' => json_encode(['ar' => 'كمبودي', 'en' => 'Cambodian'])],
            ['name' => json_encode(['ar' => 'كاميروني', 'en' => 'Cameroonian'])],
            ['name' => json_encode(['ar' => 'كندي', 'en' => 'Canadian'])],
            ['name' => json_encode(['ar' => 'تشادي', 'en' => 'Chadian'])],
            ['name' => json_encode(['ar' => 'شيلي', 'en' => 'Chilean'])],
            ['name' => json_encode(['ar' => 'صيني', 'en' => 'Chinese'])],
            ['name' => json_encode(['ar' => 'كولومبي', 'en' => 'Colombian'])],
            ['name' => json_encode(['ar' => 'كوستاريكي', 'en' => 'Costa Rican'])],
            ['name' => json_encode(['ar' => 'كرواتي', 'en' => 'Croatian'])],
            ['name' => json_encode(['ar' => 'كوبي', 'en' => 'Cuban'])],
            ['name' => json_encode(['ar' => 'قبرصي', 'en' => 'Cypriot'])],
            ['name' => json_encode(['ar' => 'تشيكي', 'en' => 'Czech'])],
            ['name' => json_encode(['ar' => 'دنماركي', 'en' => 'Danish'])],
            ['name' => json_encode(['ar' => 'جيبوتي', 'en' => 'Djiboutian'])],
            ['name' => json_encode(['ar' => 'دومينيكي', 'en' => 'Dominican'])],
            ['name' => json_encode(['ar' => 'إكوادوري', 'en' => 'Ecuadorian'])],
            ['name' => json_encode(['ar' => 'مصري', 'en' => 'Egyptian'])],
            ['name' => json_encode(['ar' => 'سلفادوري', 'en' => 'Salvadoran'])],
            ['name' => json_encode(['ar' => 'غيني استوائي', 'en' => 'Equatorial Guinean'])],
            ['name' => json_encode(['ar' => 'إريتري', 'en' => 'Eritrean'])],
            ['name' => json_encode(['ar' => 'إستوني', 'en' => 'Estonian'])],
            ['name' => json_encode(['ar' => 'إثيوبي', 'en' => 'Ethiopian'])],
            ['name' => json_encode(['ar' => 'فيجي', 'en' => 'Fijian'])],
            ['name' => json_encode(['ar' => 'فنلندي', 'en' => 'Finnish'])],
            ['name' => json_encode(['ar' => 'فرنسي', 'en' => 'French'])],
            ['name' => json_encode(['ar' => 'غابوني', 'en' => 'Gabonese'])],
            ['name' => json_encode(['ar' => 'غامبي', 'en' => 'Gambian'])],
            ['name' => json_encode(['ar' => 'جورجي', 'en' => 'Georgian'])],
            ['name' => json_encode(['ar' => 'ألماني', 'en' => 'German'])],
            ['name' => json_encode(['ar' => 'غاني', 'en' => 'Ghanaian'])],
            ['name' => json_encode(['ar' => 'يوناني', 'en' => 'Greek'])],
            ['name' => json_encode(['ar' => 'غرينادي', 'en' => 'Grenadian'])],
            ['name' => json_encode(['ar' => 'غواتيمالي', 'en' => 'Guatemalan'])],
            ['name' => json_encode(['ar' => 'غيني', 'en' => 'Guinean'])],
            ['name' => json_encode(['ar' => 'غيني بيساوي', 'en' => 'Guinea-Bissauan'])],
            ['name' => json_encode(['ar' => 'غياني', 'en' => 'Guyanese'])],
            ['name' => json_encode(['ar' => 'هايتي', 'en' => 'Haitian'])],
            ['name' => json_encode(['ar' => 'هندوراسي', 'en' => 'Honduran'])],
            ['name' => json_encode(['ar' => 'مجري', 'en' => 'Hungarian'])],
            ['name' => json_encode(['ar' => 'آيسلندي', 'en' => 'Icelandic'])],
            ['name' => json_encode(['ar' => 'هندي', 'en' => 'Indian'])],
            ['name' => json_encode(['ar' => 'إندونيسي', 'en' => 'Indonesian'])],
            ['name' => json_encode(['ar' => 'إيراني', 'en' => 'Iranian'])],
            ['name' => json_encode(['ar' => 'عراقي', 'en' => 'Iraqi'])],
            ['name' => json_encode(['ar' => 'إيرلندي', 'en' => 'Irish'])],
            ['name' => json_encode(['ar' => 'إسرائيلي', 'en' => 'Israeli'])],
            ['name' => json_encode(['ar' => 'إيطالي', 'en' => 'Italian'])],
            ['name' => json_encode(['ar' => 'جامايكي', 'en' => 'Jamaican'])],
            ['name' => json_encode(['ar' => 'ياباني', 'en' => 'Japanese'])],
            ['name' => json_encode(['ar' => 'أردني', 'en' => 'Jordanian'])],
            ['name' => json_encode(['ar' => 'كازاخستاني', 'en' => 'Kazakhstani'])],
            ['name' => json_encode(['ar' => 'كيني', 'en' => 'Kenyan'])],
            ['name' => json_encode(['ar' => 'كيريباتي', 'en' => 'Kiribati'])],
            ['name' => json_encode(['ar' => 'كوري شمالي', 'en' => 'North Korean'])],
            ['name' => json_encode(['ar' => 'كوري جنوبي', 'en' => 'South Korean'])],
            ['name' => json_encode(['ar' => 'كويتي', 'en' => 'Kuwaiti'])],
            ['name' => json_encode(['ar' => 'قيرغيزي', 'en' => 'Kyrgyz'])],
            ['name' => json_encode(['ar' => 'لاوسي', 'en' => 'Laotian'])],
            ['name' => json_encode(['ar' => 'لاتفي', 'en' => 'Latvian'])],
            ['name' => json_encode(['ar' => 'لبناني', 'en' => 'Lebanese'])],
            ['name' => json_encode(['ar' => 'ليسوتو', 'en' => 'Lesotho'])],
            ['name' => json_encode(['ar' => 'ليبيري', 'en' => 'Liberian'])],
            ['name' => json_encode(['ar' => 'ليبي', 'en' => 'Libyan'])],
            ['name' => json_encode(['ar' => 'ليختنشتايني', 'en' => 'Liechtenstein'])],
            ['name' => json_encode(['ar' => 'ليتواني', 'en' => 'Lithuanian'])],
            ['name' => json_encode(['ar' => 'لوكسمبورغي', 'en' => 'Luxembourgish'])],
            ['name' => json_encode(['ar' => 'مدغشقري', 'en' => 'Malagasy'])],
            ['name' => json_encode(['ar' => 'مالاوي', 'en' => 'Malawian'])],
            ['name' => json_encode(['ar' => 'ماليزي', 'en' => 'Malaysian'])],
            ['name' => json_encode(['ar' => 'مالديفي', 'en' => 'Maldivian'])],
            ['name' => json_encode(['ar' => 'مالي', 'en' => 'Malian'])],
            ['name' => json_encode(['ar' => 'مالطي', 'en' => 'Maltese'])],
            ['name' => json_encode(['ar' => 'مارشالي', 'en' => 'Marshallese'])],
            ['name' => json_encode(['ar' => 'موريتاني', 'en' => 'Mauritanian'])],
            ['name' => json_encode(['ar' => 'موريشي', 'en' => 'Mauritian'])],
            ['name' => json_encode(['ar' => 'مكسيكي', 'en' => 'Mexican'])],
            ['name' => json_encode(['ar' => 'ميكرونيزي', 'en' => 'Micronesian'])],
            ['name' => json_encode(['ar' => 'مولدوفي', 'en' => 'Moldovan'])],
            ['name' => json_encode(['ar' => 'موناكي', 'en' => 'Monacan'])],
            ['name' => json_encode(['ar' => 'منغولي', 'en' => 'Mongolian'])],
            ['name' => json_encode(['ar' => 'مونتينيغري', 'en' => 'Montenegrin'])],
            ['name' => json_encode(['ar' => 'مغربي', 'en' => 'Moroccan'])],
            ['name' => json_encode(['ar' => 'موزمبيقي', 'en' => 'Mozambican'])],
            ['name' => json_encode(['ar' => 'بورمي', 'en' => 'Burmese'])],
            ['name' => json_encode(['ar' => 'ناميبي', 'en' => 'Namibian'])],
            ['name' => json_encode(['ar' => 'ناورو', 'en' => 'Nauruan'])],
            ['name' => json_encode(['ar' => 'نيبالي', 'en' => 'Nepalese'])],
            ['name' => json_encode(['ar' => 'هولندي', 'en' => 'Dutch'])],
            ['name' => json_encode(['ar' => 'نيوزيلندي', 'en' => 'New Zealander'])],
            ['name' => json_encode(['ar' => 'نيكاراغوي', 'en' => 'Nicaraguan'])],
            ['name' => json_encode(['ar' => 'نيجيري', 'en' => 'Nigerian'])],
            ['name' => json_encode(['ar' => 'نيجري', 'en' => 'Nigerien'])],
            ['name' => json_encode(['ar' => 'مقدوني', 'en' => 'Macedonian'])],
            ['name' => json_encode(['ar' => 'نرويجي', 'en' => 'Norwegian'])],
            ['name' => json_encode(['ar' => 'عماني', 'en' => 'Omani'])],
            ['name' => json_encode(['ar' => 'باكستاني', 'en' => 'Pakistani'])],
            ['name' => json_encode(['ar' => 'بالاوي', 'en' => 'Palauan'])],
            ['name' => json_encode(['ar' => 'فلسطيني', 'en' => 'Palestinian'])],
            ['name' => json_encode(['ar' => 'بنمي', 'en' => 'Panamanian'])],
            ['name' => json_encode(['ar' => 'بابوي', 'en' => 'Papua New Guinean'])],
            ['name' => json_encode(['ar' => 'باراغوياني', 'en' => 'Paraguayan'])],
            ['name' => json_encode(['ar' => 'بيروفي', 'en' => 'Peruvian'])],
            ['name' => json_encode(['ar' => 'فلبيني', 'en' => 'Filipino'])],
            ['name' => json_encode(['ar' => 'بولندي', 'en' => 'Polish'])],
            ['name' => json_encode(['ar' => 'برتغالي', 'en' => 'Portuguese'])],
            ['name' => json_encode(['ar' => 'قطري', 'en' => 'Qatari'])],
            ['name' => json_encode(['ar' => 'روماني', 'en' => 'Romanian'])],
            ['name' => json_encode(['ar' => 'روسي', 'en' => 'Russian'])],
            ['name' => json_encode(['ar' => 'رواندي', 'en' => 'Rwandan'])],
            ['name' => json_encode(['ar' => 'سانت كيتس ونيفيس', 'en' => 'Kittitian/Nevisian'])],
            ['name' => json_encode(['ar' => 'سانت لوسي', 'en' => 'Saint Lucian'])],
            ['name' => json_encode(['ar' => 'سانت فنسنت', 'en' => 'Saint Vincentian'])],
            ['name' => json_encode(['ar' => 'ساموي', 'en' => 'Samoan'])],
            ['name' => json_encode(['ar' => 'سان مارينو', 'en' => 'Sammarinese'])],
            ['name' => json_encode(['ar' => 'ساو تومي وبرينسيبي', 'en' => 'Sao Tomean'])],
            ['name' => json_encode(['ar' => 'سعودي', 'en' => 'Saudi'])],
            ['name' => json_encode(['ar' => 'سنغالي', 'en' => 'Senegalese'])],
            ['name' => json_encode(['ar' => 'صربي', 'en' => 'Serbian'])],
            ['name' => json_encode(['ar' => 'سيشيلي', 'en' => 'Seychellois'])],
            ['name' => json_encode(['ar' => 'سيراليوني', 'en' => 'Sierra Leonean'])],
            ['name' => json_encode(['ar' => 'سنغافوري', 'en' => 'Singaporean'])],
            ['name' => json_encode(['ar' => 'سلوفاكي', 'en' => 'Slovak'])],
            ['name' => json_encode(['ar' => 'سلوفيني', 'en' => 'Slovene'])],
            ['name' => json_encode(['ar' => 'جزر سليمان', 'en' => 'Solomon Islander'])],
            ['name' => json_encode(['ar' => 'صومالي', 'en' => 'Somali'])],
            ['name' => json_encode(['ar' => 'جنوب أفريقي', 'en' => 'South African'])],
            ['name' => json_encode(['ar' => 'إسباني', 'en' => 'Spanish'])],
            ['name' => json_encode(['ar' => 'سريلانكي', 'en' => 'Sri Lankan'])],
            ['name' => json_encode(['ar' => 'سوداني', 'en' => 'Sudanese'])],
            ['name' => json_encode(['ar' => 'سورينامي', 'en' => 'Surinamer'])],
            ['name' => json_encode(['ar' => 'سوازيلاندي', 'en' => 'Swazi'])],
            ['name' => json_encode(['ar' => 'سويدي', 'en' => 'Swedish'])],
            ['name' => json_encode(['ar' => 'سويسري', 'en' => 'Swiss'])],
            ['name' => json_encode(['ar' => 'سوري', 'en' => 'Syrian'])],
            ['name' => json_encode(['ar' => 'طاجيكي', 'en' => 'Tajik'])],
            ['name' => json_encode(['ar' => 'تنزاني', 'en' => 'Tanzanian'])],
            ['name' => json_encode(['ar' => 'تايلاندي', 'en' => 'Thai'])],
            ['name' => json_encode(['ar' => 'تيموري', 'en' => 'Timorese'])],
            ['name' => json_encode(['ar' => 'توغولي', 'en' => 'Togolese'])],
            ['name' => json_encode(['ar' => 'تونغي', 'en' => 'Tongan'])],
            ['name' => json_encode(['ar' => 'ترينيدادي', 'en' => 'Trinidadian'])],
            ['name' => json_encode(['ar' => 'تونسية', 'en' => 'Tunisian'])],
            ['name' => json_encode(['ar' => 'تركي', 'en' => 'Turkish'])],
            ['name' => json_encode(['ar' => 'تركماني', 'en' => 'Turkmen'])],
            ['name' => json_encode(['ar' => 'توفالي', 'en' => 'Tuvaluan'])],
            ['name' => json_encode(['ar' => 'أوغندي', 'en' => 'Ugandan'])],
            ['name' => json_encode(['ar' => 'أوكراني', 'en' => 'Ukrainian'])],
            ['name' => json_encode(['ar' => 'إماراتي', 'en' => 'Emirati'])],
            ['name' => json_encode(['ar' => 'بريطاني', 'en' => 'British'])],
            ['name' => json_encode(['ar' => 'أمريكي', 'en' => 'American'])],
            ['name' => json_encode(['ar' => 'أوروغوياني', 'en' => 'Uruguayan'])],
            ['name' => json_encode(['ar' => 'أوزبكي', 'en' => 'Uzbek'])],
            ['name' => json_encode(['ar' => 'فانواتي', 'en' => 'Ni-Vanuatu'])],
            ['name' => json_encode(['ar' => 'فنزويلي', 'en' => 'Venezuelan'])],
            ['name' => json_encode(['ar' => 'فيتنامي', 'en' => 'Vietnamese'])],
            ['name' => json_encode(['ar' => 'زامبي', 'en' => 'Zambian'])],
            ['name' => json_encode(['ar' => 'زيمبابوي', 'en' => 'Zimbabwean'])]
        ];

        // إدخال البيانات في جدول الجنسيات
        DB::table('nationalities')->insert($nationalities);
    }
}
